# path: docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: thegio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: thegio-s3
    restart: always
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console/Dashboard Port
    environment:
      MINIO_ROOT_USER: minioadmin      # This is your Access Key ID
      MINIO_ROOT_PASSWORD: minioadmin  # This is your Secret Access Key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: