[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"  # or "20" depending on your needs

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"