# Netlify configuration for Thegio frontend only.

[build]
  # Build only the frontend app
  command = "cd apps/web && bun install && bun run build"

  # Publish the Next.js build output
  publish = "apps/web/.next"

# Redirect all routes to Next.js (SSR)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
