# This is the command to build the entire monorepo.
# It will run from the root of your project.
[build]
  command = "cd apps/api && bun install && bun run build && cd ../../ && cd apps/web && bun install && bun run build"
  # This is the output directory for your frontend.
  publish = "apps/web/.next"
  # This is the output directory for your compiled backend function.
  functions = "apps/api/build"

# This rule redirects all API calls to our backend function.
# The function will be named after its file, which is 'serverless.js' after compilation.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless/:splat"
  status = 200