# This is the configuration for Netlify

[build]
  # This tells Netlify where to run the build command from.
  base = "apps/web"
  # This is the build command for our Next.js frontend.
  command = "npm run build"
  # This is where the built frontend will be.
  publish = ".next"
  # This tells Netlify where our serverless backend functions are.
  functions = "netlify/functions"

# This rule redirects all API calls to our serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless"
  status = 200