[build]
  command = "cd apps/web && npm install && npm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# EXPLICITLY disable the Next.js plugin to prevent auto-detection
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false

[functions]
  node_bundler = "esbuild"