[build]
  command = "cd web && npm run build"
  publish = "web/.next"

[build.environment]
  NODE_VERSION = "18"

# REMOVE the plugin section entirely - you don't need it!
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"