# This configuration tells Netlify to ONLY build the Next.js frontend.

[build]
  # Tell Netlify where the frontend app lives.
  base = "apps/web"
  # The standard build command for a Next.js app.
  command = "bun run build"
  # The output directory for the built frontend.
  publish = ".next"