[build]
  command = "cd apps/web && npm install && npm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"
